name: swissterra
channels:
        - conda-forge

dependencies:
        - python=3.9.*
        - gdal
        - numpy
        - opencv
        - scipy
        - geopandas
        - matplotlib
        - pandas
        - python-magic
        - pygeos
        - rasterio
        - scikit-image
        - PySimpleGUI
        - cartopy
        - tqdm
        - pip
        - toml
        - graphviz
        - scikit-learn
        - earthpy
        - jinja2

        - pip:
                - https://s3-eu-west-1.amazonaws.com/download.agisoft.com/Metashape-1.7.1-cp35.cp36.cp37.cp38-abi3-linux_x86_64.whl
                - pytransform3d
