name: swissterra
channels:
        - conda-forge

dependencies:
        - python=3.9.*
        - gdal=3.1.*
        - numpy=1.19.*
        - opencv=4.5.*
        - pdal=2.2.*
        - pip=20.*
        - scipy=1.5.*
        - pip:

                - geopandas==0.8.*
                - matplotlib==3.3.*
                - pandas==1.1.*
                - python-magic==0.4.*
                - pygeos==0.8.*
                - rasterio==1.1.*
                - scikit-image==0.17.*
                - statictypes
                - PySimpleGUI
                - cartopy
                - tqdm==4.51.*
                - https://s3-eu-west-1.amazonaws.com/download.agisoft.com/Metashape-1.7.0-cp35.cp36.cp37.cp38-abi3-linux_x86_64.whl
                - toml
                  # python-pdal might not be needed
