name: swissterra
channels:
 - conda-forge
 - defaults

dependencies:
        - python=3.8.*
        - numpy=1.19.*
        - opencv=4.4.*
        - matplotlib=3.3.*
        - gdal=3.1.*
        - pdal=2.2.*
        - python-pdal=2.3.*
        - geopandas=0.8.*
        - python-magic=0.4.*
        - pandas=1.1.*
        - scikit-image=0.17.*
        - tqdm=4.50.*
        - pip=20.2.3
        - pip:
                - statictypes
                - http://download.agisoft.com/Metashape-1.6.5-cp35.cp36.cp37-abi3-linux_x86_64.whl
                - python-magic=0.4.*
